### ISSUE TITLE
More evaluation code

### ISSUE THREAD

**Issue by unknowed-ER** [unikcc/DiaASQ#7]
Thank you for your outstanding work！
In the paper, the authors provided experimental results for Span Match, Pair Extraction, and Quadruple and resulted on different cross-utterance levels. However, open-source code only provides relevant evaluations of Quadruple on all data. In order to ensure consistency in subsequent works evaluations, I sincerely hope that you can open-source code related to other experiments.
Looking forward to your reply.

**Comment by unikcc** [comment]
Certainly, we will complement them later. Thank you for your suggestion.

**Comment by unknowed-ER** [comment]
I code the experiments for Span Match and Pair Extraction. I upload the whole code [here](https://github.com/unknowed-ER/DiaASQ). However, the experimental results cannot achieve the results reported in the paper. What is the problem? Plz.

The  experimental results on zh dataset are the following:
```
2023-06-15 22:44:32.622 | INFO     | __main__:forward:130 - Start to eval...
100%|█████████████████████████████████████████| 100/100 [00:08<00:00, 11.92it/s]
Span Match (F1)
Target	Aspect	Opinion
46.76	40.72	32.85
Pair Extraction (F1)
T-A	T-O	A-O
25.95	26.79	25.28
2023-06-15 22:44:41.186 | INFO     | src.utils:save2file:244 - Save prediction results to data/save/pred_zh_test.json
2023-06-15 22:44:41.194 | INFO     | __main__:evaluate:78 - Evaluate on test set, micro-F1 score: 30.8756%
Item	Prec.	Rec.	F1	TP	Pred.	Gold.
Micro	0.2702	0.3602	0.3088	201	744	558
Iden	0.3347	0.4462	0.3825	249	744	558
```

**Comment by unikcc** [comment]
Regarding the quadruple extraction, when running the code with the default settings, the scores can easily surpass or closely approximate the reported ones. I noticed that you changed the batch size to 1, which might be one of the reasons causing the problem.

Concerning the span extraction, we utilize the annotated spans in the 'target', 'aspect', and 'opinion' fields as the golden set, rather than the spans within the quadruples.
For pair extraction, we consider all combinations of pairs within the quadruples as the golden set.

I currently have some other urgent tasks to attend to. You can now focus on the quadruple extraction, and we will update the other metrics as soon as possible.

**Comment by unknowed-ER** [comment]
Thank you for your reply.
